name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.20', '1.21', '1.22' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Gather dependencies
        run: go mod download
      - name: test
        run: go test -coverprofile=coverage.txt -covermode=atomic
      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
